### ISSUE TITLE
support to pass values

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfnotify#28]
```
$ tfnotify plan -var `label_prefix:foo`
```

```yaml
    when_add_or_update_only:
      label: "{{.Vars.label_prefix}}/add-or-update"
      label_color: "1d76db"  # blue
```
